export const TRANSPORTATION_TYPES = {
  FLIGHT: "Flight",
  TRAIN: "Train",
  CAR: "Car",
  BUS: "Bus",
};

const TRANSPORTATION__ILLUSTRATIONS_BASE_URL = "/cardIllustrations";
export const TRANSPORTATION_ILLUSTRATIONS = {
  [TRANSPORTATION_TYPES.FLIGHT]:
    TRANSPORTATION__ILLUSTRATIONS_BASE_URL + "/airport.svg",
  [TRANSPORTATION_TYPES.TRAIN]:
    TRANSPORTATION__ILLUSTRATIONS_BASE_URL + "/subway.svg",
  [TRANSPORTATION_TYPES.CAR]:
    TRANSPORTATION__ILLUSTRATIONS_BASE_URL + "/fast_car.svg",
  [TRANSPORTATION_TYPES.BUS]:
    TRANSPORTATION__ILLUSTRATIONS_BASE_URL + "/bus_stop.svg",
};
